Create and test endpoint for posting a new comment
MarKo-ctrl/BE_NC-News pull request #11
Opened 2022-05-19 14:04 UTC by MarKo-ctrl

2022-05-19 14:59 UTC, DCrawley94 commented on __tests__/app.test.js
> +    });
Rememebr to test behaviour for a valid but none-existant ID.

Also what if the given username does not exist? How does the endpoint behave then?
What is data is missing from the request body?

2022-05-20 08:41 UTC, elijaharley requested changes
Hi Marios, I've left a couple of notes - one to do with formatting in tests which is minor, but the other in the model is important. Let me know if you have any questions about this and I'll be happy to go over it with you.

2022-05-20 08:41 UTC, elijaharley commented on __tests__/app.test.js
> +    });
Looking good Marios, I'd consider accessing rows[0] in your models rather than your tests as a potential refactor for tidiness.

2022-05-20 08:41 UTC, elijaharley commented on models/articles.models.js
> +};
There are 3 queries currently for this endpoint, however the first two are just for the purpose of error handling. We want to make as few requests to our db as possible as this will slow down our requests, especially if our project is scaled up to take a lot of traffic. try commenting out the first two queries to see what happens. If you log your error in your psql errors error handler you should be able to handle this functionality there without additional queries to the db.

I'd also recommend breaking the queries for the comments out into a separate model.

2022-05-20 10:13 UTC, elijaharley approved these changes
Great stuff Marios - looking really nice now

2022-05-20 10:16 UTC, merged